version: '3.7'

services:
  db:
    image: 'postgres:alpine'
    container_name: "app_db"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: users
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    ports:
      - "5435:5435"

  user:
    depends_on:
      - db
    container_name: "app_user"
    build: .
    volumes:
      - ./:/app
    ports:
      - 8085:8085
